In [1]:
import pandas as pd
import numpy as np
from sklearn import preprocessing
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split 

In [2]:
data1 = pd.read_csv("train.csv") 

In [3]:
data1.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [4]:
data1=data1.drop(['Name','Ticket','Cabin','PassengerId'],axis = 1)

In [5]:
data1.head()

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

In [6]:
data1.columns

Index(['Survived', 'Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare',
       'Embarked'],
      dtype='object')

In [7]:
label = preprocessing.LabelEncoder()

In [8]:
data1['Sex'] = label.fit_transform(data1['Sex'])
data1['Embarked'] = label.fit_transform(data1['Embarked'])

In [9]:
data1.head()

Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0         0       3    1  22.0      1      0   7.2500         2
1         1       1    0  38.0      1      0  71.2833         0
2         1       3    0  26.0      0      0   7.9250         2
3         1       1    0  35.0      1      0  53.1000         2
4         0       3    1  35.0      0      0   8.0500         2

In [16]:

data1.columns

Index(['Survived', 'Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare',
       'Embarked'],
      dtype='object')

In [17]:
from sklearn.naive_bayes import *

In [24]:
columns = ['Survived', 'Pclass', 'Sex', 'SibSp', 'Parch', 
       'Embarked']

In [27]:
for i in columns:
    y=data1[i]
    X=data1.drop(i,axis=1)
    X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=0)
    clf = BernoulliNB()
    print("\nDependent Variable is : " ,i)
    y_pred = clf.fit(X_train,y_train).predict(X_test)
    print("Accuracy Score is : ",accuracy_score(y_test,y_pred,normalize=True))
    print("Confusion Matrix is : \n",confusion_matrix(y_test,y_pred))
    print("---------------------------------------------------------------")


Dependent Variable is :  Survived
Accuracy Score is :  0.7715355805243446
Confusion Matrix is : 
 [[131  26]
 [ 35  75]]
---------------------------------------------------------------

Dependent Variable is :  Pclass
Accuracy Score is :  0.5917602996254682
Confusion Matrix is : 
 [[ 30   8  32]
 [  9  10  30]
 [ 24   6 118]]
---------------------------------------------------------------

Dependent Variable is :  Sex
Accuracy Score is :  0.7453183520599251
Confusion Matrix is : 
 [[ 49  49]
 [ 19 150]]
---------------------------------------------------------------

Dependent Variable is :  SibSp
Accuracy Score is :  0.6891385767790262
Confusion Matrix is : 
 [[162  20   0   0   0   0   0]
 [ 43  22   0   0   0   0   0]
 [  6   2   0   0   0   0   0]
 [  5   2   0   0   0   0   0]
 [  2   0   0   0   0   0   0]
 [  1   0   0   0   0   0   0]
 [  2   0   0   0   0   0   0]]
---------------------------------------------------------------

Dependent Variable is :  Parch
Accuracy Score i