In [2]:
print("ahmed")

ahmed


In [3]:
import numpy as np

Que 1:

In [19]:
arr1 = np.random.random((3,3,3))

In [20]:
print(arr1)

[[[0.88774896 0.80247544 0.37105185]
  [0.18580808 0.20432886 0.95571124]
  [0.38820692 0.76041687 0.14051632]]

 [[0.08611123 0.88429968 0.75226626]
  [0.12422588 0.01303833 0.22143613]
  [0.49507987 0.12797246 0.3853634 ]]

 [[0.19958454 0.34295114 0.47283719]
  [0.89080315 0.130173   0.75185079]
  [0.15812101 0.89551686 0.09611766]]]


In [23]:
print(type(arr1))
print(arr1.shape)

<class 'numpy.ndarray'>
(3, 3, 3)


Que 2 :

In [48]:
arr2 = np.diag(np.arange(5),k=0)
print(arr2)

[[0 0 0 0 0]
 [0 1 0 0 0]
 [0 0 2 0 0]
 [0 0 0 3 0]
 [0 0 0 0 4]]


In [45]:
print(type(arr2))
print(arr2.shape)

<class 'numpy.ndarray'>
(5, 5)


Que 3 :

In [72]:
arr3 = np.ones((8,8))
arr3[1::2,::2] = 0
arr3[::2,1::2] = 0 
print(arr3)
print("Shape of mtrix")
print(arr3.shape)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]
Shape of mtrix
(8, 8)


Que 4 :

Que 5 :

In [80]:
arr4 = np.array([10,20,30])
arr5 = np.array([20,30,40])
print("common values: ")
arr6 = (np.intersect1d(arr4,arr5))
print(arr6)

common values: 
[20 30]


Que 6 :

In [89]:
yest = np.datetime64('today', 'D') - 1
print("Yesterady was: ",yest)
today = np.datetime64('today', 'D')
print("Today is: ",today)
tomm = np.datetime64('today', 'D') + 1
print("Tommorow is: ",tomm)


Yesterady was:  2020-07-25
Today is:  2020-07-26
Tommorow is:  2020-07-27


Que 7 :

In [104]:
arr2 = np.random.random(6)
arr3 = np.random.random(6)
print(arr2)
print("\n",arr3)
equ = np.array_equal(arr2,arr3)
print("\n",equ)




[0.85835605 0.88320298 0.50791545 0.2883295  0.71329568 0.34916142]

 [0.39669397 0.08218282 0.24566611 0.7488148  0.26069216 0.04798673]

 False


Que 8:


In [113]:
import numpy as np
arr4 = np.random.random(10)
print("Original array :\n",arr4)

arr4[arr4.argmax()] = 0
print("After finding the max number: ")
print(arr4)




Original array :
 [0.27740279 0.5084668  0.55926836 0.91876046 0.84914793 0.83179967
 0.18392938 0.52680613 0.2308737  0.00126488]
After finding the max number: 
[0.27740279 0.5084668  0.55926836 0.         0.84914793 0.83179967
 0.18392938 0.52680613 0.2308737  0.00126488]


Que 9 :

In [114]:
arr4 = np.random.random(10)
print(arr4)

[0.80585736 0.7522635  0.75481389 0.24382944 0.72325533 0.88610293
 0.6584711  0.52583173 0.9066349  0.78131887]


Que 10 :

In [42]:
arr5 = np.random.randint(1, 10, (3,3))
print("Matrix is :\n",arr5)
mean = arr5.mean(axis=1)
print("Mean of row is :\n ",mean)
sub = arr5 - mean
print("Substracton is :\n",sub)

Matrix is :
 [[2 5 8]
 [6 9 6]
 [6 6 7]]
Mean of row is :
  [5.         7.         6.33333333]
Substracton is :
 [[-3.         -2.          1.66666667]
 [ 1.          2.         -0.33333333]
 [ 1.         -1.          0.66666667]]


Que 11:

Que 12: 

In [117]:
arr4 = np.array([[1, 2], [4, 3]])
arr5 = np.array([[1, 2], [4, 3]])
print(arr4)
print(arr5)

ans = np.diag(np.dot(arr4,arr5))
print("DOT Product is : ",ans)

[[1 2]
 [4 3]]
[[1 2]
 [4 3]]
DOT Product is :  [ 9 17]


Que 13 :

In [126]:
arr6 = np.random.randint(0,10,30)
print(arr6)
most_freq = np.bincount(arr6).argmax()
print("Most frequent number is :",most_freq)

[1 0 2 9 4 8 9 7 5 5 1 7 5 6 2 2 3 0 9 2 2 9 7 7 1 9 9 9 3 7]
Most frequent number is : 9


Que 14 :

In [12]:

n = int(input("How many values?"))
arr6 = np.random.randint(0, 10*10,20)
print(arr6)
b=np.unique(arr6)
ans = list(b[-n:])
desc = ans[::-1]
print("The values are : ",desc)


How many values?3
[47 33 46  9 56  3 60 39 70 28 17 89 21 39 49 58 58  3 50 34]
The values are :  [89, 70, 60]


Que 15 :

In [27]:
arr7 = np.array([1,2,3,4])
arr8 = np.array(['ahmed','morve','letsupgrade','amd'])
rec_arr = np.core.records.fromarrays([arr7,arr8])
print(rec_arr[0])
print(rec_arr[1])
print(rec_arr[2])
print(rec_arr[3])

print(type(rec_arr))

(1, 'ahmed')
(2, 'morve')
(3, 'letsupgrade')
(4, 'amd')
<class 'numpy.recarray'>
